name: Release

on:
  push:
    tags: 
    - 'v[0-9]+.[0-9]+.[0-9]+*'

defaults:
  run:
    shell: pwsh

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:    
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1
          6.0

    - name: Create Release
      run: Import-Module ./release.ps1 && Publish-Release -Tag $env:GITHUB_REF.Split("/")[-1]
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
